spring.application.name=stranger-chat

server.port=${PORT:8081}
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}
spring.redis.username=${SPRING_REDIS_USERNAME:}
spring.redis.password=${SPRING_REDIS_PASSWORD:}
